In [429]:
#import Machine learning packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import *
from sklearn.impute import *

In [524]:
#importing data
data_set = pd.read_csv('data.csv')
# independent feature
X = data_set.iloc[:,:-1].values
# dependent features
y = data_set.iloc[:,3].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 57.0, 67000.0]], dtype=object)

In [525]:
# Fixing missing values
imputer = SimpleImputer(missing_values=np.nan ,strategy="mean")
imputer = imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

In [526]:
#encoding the categorical features
labelEncoder_X = LabelEncoder()
labelEncoder_X.fit(X[:,0])
X[:,0] = labelEncoder_X.transform(X[:,0])
#converting catgorical data to column
onehotencoder = OneHotEncoder()
X = np.append(X,onehotencoder.fit_transform(X[:,0].reshape(-1, 1)).toarray()
,axis=1) 
X

array([[0, 44.0, 72000.0, 1.0, 0.0, 0.0],
       [2, 27.0, 48000.0, 0.0, 0.0, 1.0],
       [1, 30.0, 54000.0, 0.0, 1.0, 0.0],
       [2, 38.0, 61000.0, 0.0, 0.0, 1.0],
       [1, 40.0, 63777.77777777778, 0.0, 1.0, 0.0],
       [0, 35.0, 58000.0, 1.0, 0.0, 0.0],
       [2, 41.0, 52000.0, 0.0, 0.0, 1.0],
       [0, 48.0, 79000.0, 1.0, 0.0, 0.0],
       [1, 50.0, 83000.0, 0.0, 1.0, 0.0],
       [0, 57.0, 67000.0, 1.0, 0.0, 0.0]], dtype=object)

In [527]:
X = np.delete(X,np.s_[0], axis = 1)

In [528]:
X

array([[44.0, 72000.0, 1.0, 0.0, 0.0],
       [27.0, 48000.0, 0.0, 0.0, 1.0],
       [30.0, 54000.0, 0.0, 1.0, 0.0],
       [38.0, 61000.0, 0.0, 0.0, 1.0],
       [40.0, 63777.77777777778, 0.0, 1.0, 0.0],
       [35.0, 58000.0, 1.0, 0.0, 0.0],
       [41.0, 52000.0, 0.0, 0.0, 1.0],
       [48.0, 79000.0, 1.0, 0.0, 0.0],
       [50.0, 83000.0, 0.0, 1.0, 0.0],
       [57.0, 67000.0, 1.0, 0.0, 0.0]], dtype=object)

In [529]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [530]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [531]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [532]:
X_train

array([[40.0, 63777.77777777778, 0.0, 1.0, 0.0],
       [57.0, 67000.0, 1.0, 0.0, 0.0],
       [27.0, 48000.0, 0.0, 0.0, 1.0],
       [41.0, 52000.0, 0.0, 0.0, 1.0],
       [48.0, 79000.0, 1.0, 0.0, 0.0],
       [38.0, 61000.0, 0.0, 0.0, 1.0],
       [44.0, 72000.0, 1.0, 0.0, 0.0],
       [35.0, 58000.0, 1.0, 0.0, 0.0]], dtype=object)

In [533]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [534]:
X_test

array([[30.0, 54000.0, 0.0, 1.0, 0.0],
       [50.0, 83000.0, 0.0, 1.0, 0.0]], dtype=object)

In [535]:
y_test

array([0, 0])

In [536]:
# feature scaling with StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [538]:
X_train

array([[-0.1500075 ,  0.12381479, -1.        ,  2.64575131, -0.77459667],
       [ 1.89009451,  0.46175632,  1.        , -0.37796447, -0.77459667],
       [-1.71008551, -1.53093341, -1.        , -0.37796447,  1.29099445],
       [-0.0300015 , -1.11141978, -1.        , -0.37796447,  1.29099445],
       [ 0.8100405 ,  1.7202972 ,  1.        , -0.37796447, -0.77459667],
       [-0.3900195 , -0.16751412, -1.        , -0.37796447,  1.29099445],
       [ 0.3300165 ,  0.98614835,  1.        , -0.37796447, -0.77459667],
       [-0.7500375 , -0.48214934,  1.        , -0.37796447, -0.77459667]])

In [539]:
X_test

array([[-1.35006751, -0.90166297, -1.        ,  2.64575131, -0.77459667],
       [ 1.0500525 ,  2.13981082, -1.        ,  2.64575131, -0.77459667]])