In [429]:
#import Machine learning packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import *
from sklearn.impute import *

In [498]:
#importing data
data_set = pd.read_csv('data.csv')
# independent feature
X = data_set.iloc[:,:-1].values
# dependent features
y = data_set.iloc[:,3].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 57.0, 67000.0]], dtype=object)

In [499]:
# Fixing missing values
imputer = SimpleImputer(missing_values=np.nan ,strategy="mean")
imputer = imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

In [500]:
#encoding the categorical features
labelEncoder_X = LabelEncoder()
labelEncoder_X.fit(X[:,0])
X[:,0] = labelEncoder_X.transform(X[:,0])
#converting catgorical data to column
onehotencoder = OneHotEncoder()
X = np.append(X,onehotencoder.fit_transform(X[:,0].reshape(-1, 1)).toarray()
,axis=1) 
X

array([[0, 44.0, 72000.0, 1.0, 0.0, 0.0],
       [2, 27.0, 48000.0, 0.0, 0.0, 1.0],
       [1, 30.0, 54000.0, 0.0, 1.0, 0.0],
       [2, 38.0, 61000.0, 0.0, 0.0, 1.0],
       [1, 40.0, 63777.77777777778, 0.0, 1.0, 0.0],
       [0, 35.0, 58000.0, 1.0, 0.0, 0.0],
       [2, 41.0, 52000.0, 0.0, 0.0, 1.0],
       [0, 48.0, 79000.0, 1.0, 0.0, 0.0],
       [1, 50.0, 83000.0, 0.0, 1.0, 0.0],
       [0, 57.0, 67000.0, 1.0, 0.0, 0.0]], dtype=object)

In [501]:
X = np.delete(X,np.s_[0], axis = 1)

In [502]:
X

array([[44.0, 72000.0, 1.0, 0.0, 0.0],
       [27.0, 48000.0, 0.0, 0.0, 1.0],
       [30.0, 54000.0, 0.0, 1.0, 0.0],
       [38.0, 61000.0, 0.0, 0.0, 1.0],
       [40.0, 63777.77777777778, 0.0, 1.0, 0.0],
       [35.0, 58000.0, 1.0, 0.0, 0.0],
       [41.0, 52000.0, 0.0, 0.0, 1.0],
       [48.0, 79000.0, 1.0, 0.0, 0.0],
       [50.0, 83000.0, 0.0, 1.0, 0.0],
       [57.0, 67000.0, 1.0, 0.0, 0.0]], dtype=object)

In [503]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [504]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])